[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["chmod +x frontend/build.sh", "chmod +x frontend/start.sh"]

[phases.build]
cmds = ["cd frontend && ./build.sh"]

[phases.start]
cmd = "cd frontend && ./start.sh"
