[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["chmod +x build-frontend.sh"]

[phases.build]
cmds = ["./build-frontend.sh"]

[phases.start]
cmd = "npx serve -s build -l 3000"
