[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = [
  "cp frontend/package.json .",
  "cp -r frontend/src .",
  "cp -r frontend/public .",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npx serve -s build -l 3000"
