# Railway Configuration for EscaShop
# This will deploy backend and frontend as separate services
# Database should be added separately as PostgreSQL service in Railway dashboard

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1
sleepApplication = false

# Backend service configuration
[[services]]
name = "escashop-backend"
source = "backend"

[services.escashop-backend.build]
buildCommand = "npm ci && npm run build"

[services.escashop-backend.deploy]
startCommand = "npm run migrate:railway && npm start"
healthcheckPath = "/health"

[services.escashop-backend.variables]
NODE_ENV = "production"
NODE_VERSION = "20"
PORT = "5000"

# Frontend service configuration
[[services]]
name = "escashop-frontend"
source = "frontend"

[services.escashop-frontend.build]
buildCommand = "npm ci && npm run build"

[services.escashop-frontend.deploy]
startCommand = "npx serve -s build -l 3000"

[services.escashop-frontend.variables]
NODE_ENV = "production"
NODE_VERSION = "20"
